###
http://clients1.google.com/generate_204

###
http://clients2.google.com/generate_204

###
http://clients3.google.com/generate_204

###
http://clients4.google.com/generate_204

###
http://clients.l.google.com/generate_204

###
http://connectivitycheck.android.com/generate_204

###
http://connectivitycheck.gstatic.com/generate_204


